language: python
sudo: required
python:
  - 3.5
  - 3.6
install:
  - sudo apt-get install build-essential python-dev libmysqlclient-dev
  - pip install virtualenv
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt
script:
  - bash ./SETUP_API.sh
