language: python
sudo: required
python:
  - 3.5
before_install:
  - sudo apt-get install build-essential python-dev libmysqlclient-dev
env:
  global:
    - DECLASS_API_USER=$DECLASS_API_USER
    - DECLASS_API_PW=$DECLASS_API_PW
script:
  - echo DECLASS_API_USER
  - echo $TRAVIS_SECURE_ENV_VARS
  - bash ./SETUP_API.sh
