language: python
sudo: required
python:
  - 3.5
  - 3.6
before_install:
  - sudo apt-get install build-essential python-dev libmysqlclient-dev
install:
  - python setup.py install
script:
  - python test.py
